// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzuRRBfjuxiO15grMDMsibQS2Qr4IL17U',
    appId: '1:545384142045:android:fbbd590cb5cf92e7ba3734',
    messagingSenderId: '545384142045',
    projectId: 'localtour-e640a',
    storageBucket: 'localtour-e640a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyrpzHYqsC6oLbOSX7_tmotG_gHk5M_fg',
    appId: '1:545384142045:ios:82465c04e0acb3afba3734',
    messagingSenderId: '545384142045',
    projectId: 'localtour-e640a',
    storageBucket: 'localtour-e640a.firebasestorage.app',
    iosClientId: '545384142045-77hoplmnc2os1sirtcacbp0i1uim097n.apps.googleusercontent.com',
    iosBundleId: 'com.example.localtourapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyrpzHYqsC6oLbOSX7_tmotG_gHk5M_fg',
    appId: '1:545384142045:ios:82465c04e0acb3afba3734',
    messagingSenderId: '545384142045',
    projectId: 'localtour-e640a',
    storageBucket: 'localtour-e640a.firebasestorage.app',
    iosClientId: '545384142045-77hoplmnc2os1sirtcacbp0i1uim097n.apps.googleusercontent.com',
    iosBundleId: 'com.example.localtourapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClkthQhttWgxlCxK5tmzjRiUpDIsFlvVE',
    appId: '1:545384142045:web:b33be7b81dec4cb4ba3734',
    messagingSenderId: '545384142045',
    projectId: 'localtour-e640a',
    authDomain: 'localtour-e640a.firebaseapp.com',
    storageBucket: 'localtour-e640a.firebasestorage.app',
    measurementId: 'G-HM5Z4XJL78',
  );
}
